import { Container } from '@chakra-ui/react'
import Logo from 'components/Logo'
import Main from 'components/Main'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container border="4px" borderColor="purple.500">
        <Main />
        <Logo />
      </Container>
    </div>
  )
}

export default Home
