import { Container, VStack } from '@chakra-ui/react'
import Logo from 'components/Logo'
import Main from 'components/Main'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <VStack backgroundColor="yellow.500">
      <Container
        maxW="container.xl"
        border="4px"
        borderColor="purple.500"
        centerContent
        h="100vh"
      >
        <Head>
          <title>Burger App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Main />
        <Logo size="huge" />
      </Container>
    </VStack>
  )
}

export default Home
